### ISSUE TITLE
Document API methods in schema.yaml

### ISSUE THREAD

**Issue by MasonEgger** [MasonEgger/digitalocean-classroom#8]
Many methods don't have proper documentation in the schema.yaml. I tend to just live edit these in the online swagger editor and then copy the yaml back https://editor.swagger.io/

**Comment by hacktoberfesttempaccount1234** [comment]
Hi! I tried adding a documentation https://github.com/MasonEgger/digitalocean-classroom/pull/11, I'm new to hacktoberfest, let me know if it is right!

**Comment by MasonEgger** [comment]
Look into drf_spectacular

**Comment by MasonEgger** [comment]
Moved to drf_spectacular, this is no longer relevant. Will open relevant issues needed
